### ISSUE TITLE
Re-enable camelcase linting rule

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5457]
Removing [this line](https://github.com/mozilla/treeherder/blob/master/.eslintrc.js#L28) will require touching code in lots of other files.

**Comment by rbrishabh** [comment]
Hey! Can I take this up? :)

**Comment by armenzg** [comment]
Go for it!

**Comment by Shivansh2407** [comment]
@armenzg Can I take up this issue? Please explain me a bit about this too

**Comment by armenzg** [comment]
I can open few more issues like this so you can all work on different ones.
One for each rule.

@rbrishabh let me open few more

For the record, there's more to this than removing the rule. The tests also need to pass.

@Shivansh2407 run `yarn lint` to see what needs fixing.

**Comment by armenzg** [comment]
@rbrishabh I have not yet marked these issues as "good first issues" so you can pick first:
https://github.com/mozilla/treeherder/issues

Thank you both for your help!

**Comment by rbrishabh** [comment]
@Shivansh2407 That's okay man. Go ahead and work on this one! Good luck =)

**Comment by armenzg** [comment]
@Shivansh2407 any progress?
If you won't have a PR in a while let's see if @VCDmoose could help here. Thanks!

**Comment by peterchou3788** [comment]
Hello armenzg!
Is this issue still open? I would like to work on it if possible.

**Comment by armenzg** [comment]
@peterchou3788 Feel free to grab it. Make sure `yarn lint` works before opening a PR.

**Comment by eralwen** [comment]
Can I tackle this issue if this is open? Are you just removing this line from the line and fixing all the errors that arise?

**Comment by armenzg** [comment]
@eralwen that's correct. Feel free to grab as I have not heard back from anyone else.

**Comment by armenzg** [comment]
@eralwen thanks for trying!

**Comment by MusaTalluzi** [comment]
@armenzg I see eralwen closed his PR, can I grab it?

**Comment by armenzg** [comment]
@MusaTalluzi you may; try to see if you can re-use what he had working. Thank you!
