### ISSUE TITLE
Remove ElasticSearch code

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5524]
Once upon a time we had an ElasticSearch add-on, however, we don't have it for a while.

Before you tackling this issue, check with me.
I'm waiting to see if someone will raise an objection in [here](https://groups.google.com/forum/#!topic/mozilla.tools.treeherder/-Dgulh0-Tng).

You can see some of the code that will need removing in [here](https://github.com/mozilla/treeherder/search?q=ElasticSearch&type=Code).

**Comment by sh0aibsha1kh** [comment]
Hi Armen, can I take this bug?

**Comment by armenzg** [comment]
Please do so. Thanks!
