### ISSUE TITLE
Clear test warnings for Filtering_test.jsx

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5721]
This is the warngs we get:
```bash
% yarn test tests/ui/job-view/Filtering_test.jsx
yarn run v1.19.2
$ node ./node_modules/jest/bin/jest tests/ui/job-view/Filtering_test.jsx
 PASS  tests/ui/job-view/Filtering_test.jsx (11.762s)
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: The prop `children` is marked as required in `Pane`, but its value is `undefined`.
          in Pane (created by SplitPane)
          in SplitPane (at App.jsx:340)
          in div (created by FocusTrap)
          in FocusTrap (created by HotKeys)
          in HotKeys (at KeyboardShortcuts.jsx:239)
          in KeyboardShortcuts (created by ConnectFunction)
          in ConnectFunction (at App.jsx:321)
          in Provider (at App.jsx:320)
          in div (at App.jsx:319)
          in App (at Filtering_test.jsx:104)
    console.warn node_modules/react-dom/cjs/react-dom.development.js:12357
      Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

      * Move code with side effects to componentDidMount, and set initial state in the constructor.
      * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: HotKeys
    console.warn node_modules/react-dom/cjs/react-dom.development.js:12357
      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: Modal
    console.warn node_modules/react-dom/cjs/react-dom.development.js:12357
      Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

      * Move data fetching code or side effects to componentDidUpdate.
      * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: Modal


Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        12.336s, estimated 16s
Ran all test suites matching /tests\/ui\/job-view\/Filtering_test.jsx/i.
✨  Done in 13.73s.
```

**Comment by Manish-Giri** [comment]
I'd like to work on this...

**Comment by armenzg** [comment]
Hi @Manish-Giri go for it! Thanks!

**Comment by Manish-Giri** [comment]
@armenzg After some digging, I have the following updates - 

1. The first warning about `undefined prop children` goes away if I wrap the additional content in children of `SplitPane` in `job-view/App.jsx` after the first `div`- 
https://github.com/mozilla/treeherder/blob/fc1e660053b4c636d0820ec44b9475518263db76/ui/job-view/App.jsx#L376-L385
 in another `div`, like so -
```js
              <div>
                {currentRepo && (
                  <DetailsPanel
                    resizedHeight={detailsHeight}
                    currentRepo={currentRepo}
                    repoName={repoName}
                    user={user}
                    classificationTypes={classificationTypes}
                    classificationMap={classificationMap}
                  />
                )}
              </div>
```

2. The second warning about the usage of the `componentWillMount()` lifecycle method (more details on [React: async rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)) is from the [react-hotkeys](https://github.com/greena13/react-hotkeys/issues/128) library. There have been two issues logged over there about this - https://github.com/greena13/react-hotkeys/issues/128 and https://github.com/greena13/react-hotkeys/issues/151, and it seems that all unsafe lifecycle methods have been removed in the latest release `v2.0.0`.  (Note - _I manually changed the version in `package.json` and confirmed this warning doesn't exist in `v2.0.0`. There is, however, another related warning after upgrading to v2 - `Warning: Received true for a non-boolean attribute focused`_). However, I found that react-hotkeys was upgraded here to `v2.0.0` in August in https://github.com/mozilla/treeherder/commit/33e61ddbec2aa83f229bb987ad941c96229710d1 but then it was reverted back to `v1.1.4` in https://github.com/mozilla/treeherder/commit/b961adf761f8f7140bc297866dde21a5ca866fdf, so I'm guessing we can't upgrade to v2.

3. The remaining two warnings about the usage of `componentWillUpdate()` and `componentWillReceiveProps()` is from the `Modal` component in the [reactstrap](https://github.com/reactstrap/reactstrap) library. Issues logged over there about this are - https://github.com/reactstrap/reactstrap/issues/1159 and https://github.com/reactstrap/reactstrap/issues/1340, but there is no info. on when/if these methods will be removed.

Please let me know your thoughts on this. I can submit a PR for the first warning fix, if you approve.

**Comment by armenzg** [comment]
For point 1, would a React fragment do the trick? Go head with part 1.

With regards to react-hot-keys major update is because it breaks the normal behaviour of a hot key scenario.

In this page you can read the manual test case #8 :
https://treeherder.readthedocs.io/testcases.html#treeherder

You can easily test it on this page:
https://treeherder.allizom.org/#/jobs?repo=autoland

Upgrading the package would requirying looking at the upgrade doc:
https://github.com/greena13/react-hotkeys/releases/tag/v2.0.0

Should we create a different issue to simply focus on upgrading react-hotkeys?

Thanks for thorough update!

**Comment by Manish-Giri** [comment]
@armenzg Thank You for the confirmation. I used React Fragment and created a PR for  Part 1.

For Part 2, about the `react-hotkeys` major version update, I also feel it needs more in-depth investigation and looking at the release docs, so it would probably be a good idea to create a separate issue about this, and track all the details there. Using version 2 also creates a console error in `Filtering_test.jsx`, so that also needs to be looked into. 

If you prefer, I could work on that issue as well, since I've already done some digging into react-hotkeys.

**Comment by armenzg** [comment]
I've filed issue #5786 for the upgrade. It would be great if you could tackle it. Thank you!

PS: We will all be out until Jan. 2nd.

**Comment by armenzg** [comment]
Thank you for the PR!

If I got it right I believe this is the first Treeherder code landing.
Congratulations! 🎉

**Comment by Manish-Giri** [comment]
@armenzg Thank You! This was indeed my first contribution to Treeherder! 

I'll get started with #5786.
