### ISSUE TITLE
Upgrade to react-hotkeys

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5786]
Upgrading `react-hot-keys` requires some work. When I landed it back in the day it broke the UI. [Manual test case #8](https://treeherder.readthedocs.io/testcases.html#treeherder) is the one that covers it.

**Comment by parshva-b** [comment]
Hey, @armenzg  I would like to **claim this issue** as my first contribution, would appreciate some guidance or referral docs to help me set up the environment.

**Comment by armenzg** [comment]
Hi @parshva-b 
I just fixed this issue in the last few days: https://github.com/mozilla/treeherder/pull/5820

You can make other contributions like clearing a warning at a time from the test runs:
https://travis-ci.org/mozilla/treeherder/jobs/638326849
Or to increase the project's code coverage.

**Comment by armenzg** [comment]
Hi @parshva-b 
I thought I had fixed this issue, however, I was wrong.
If you're still interested please let me know.

You can see in this video how the feature is broken:
https://bug1610350.bmoattachments.org/attachment.cgi?id=9121881

Once the user pressed the 'U' letter on their keyboard they should have only seen the jobs saying 'wpt16'.
If you go to https://treeherder.mozilla.org/#/jobs?repo=autoland you can test the expected behaviour.

**Comment by jaskeerat789** [comment]
![Screenshot from 2020-01-21 13-04-10](https://user-images.githubusercontent.com/38110126/72784357-a3b6c000-3c4e-11ea-8767-e004f0cc0717.png)
so you are saying that the screen should show only the jobs saying "GTest" when the user presses U on the keyboard...
I think i can work on this...

**Comment by parshva-b** [comment]
@armenzg I can work on this issue, can it be assigned?
Can you link to dev docs?

**Comment by armenzg** [comment]
@jaskeerat789 We will continue with @parshva-b due to first contact.

@parshva-b go ahead and work on it. https://treeherder.readthedocs.io
Let's assume it is assigned to you.

**Comment by armenzg** [comment]
Keeping in here the comment I made in ths PR

Start the app with `yarn start:stage` (this will give you a lot of jobs that are not classified - i.e. orange jobs without a star) and load this url: http://localhost:5000/#/jobs?repo=mozilla-central&revision=be3a05f615a557fd4c5171f789cc460688d9c3b8

Correct behaviour (no matter how many times I press U we will only see the R2 job):
![Screen Recording 2020-01-22 at 02 17 PM](https://user-images.githubusercontent.com/44410/72926180-fb722b80-3d21-11ea-8f37-777864dfa294.gif)

Invalid behaviour (it shows all orange jobs instead of just the R2 job):
![Screen Recording 2020-01-22 at 02 14 PM](https://user-images.githubusercontent.com/44410/72925969-961e3a80-3d21-11ea-9df0-fdb9a0db0eab.gif)

**Comment by jaskeerat789** [comment]
@parshva-b are you still working on this?

**Comment by parshva-b** [comment]
@jaskeerat789, I seem to be busy at the moment, feel free to work on it.

**Comment by govardhan27** [comment]
Hey am gonna take up this task

**Comment by jaskeerat789** [comment]
@govardhan27 I am already working on it sir...

**Comment by govardhan27** [comment]
@jaskeerat789 alright!
Let me know if you need any help.

**Comment by jaskeerat789** [comment]
ya sure

**Comment by SuyashSalampuria** [comment]
If no one is working on it , I would like to take it up.

**Comment by armenzg** [comment]
Speak up if you're working on this, otherwise, let's leave room for other newcomers.

**Comment by jaskeerat789** [comment]
I am not working on it!!!

**Comment by SuyashSalampuria** [comment]
> Speak up if you're working on this, otherwise, let's leave room for other newcomers.

I deleted my message with the same intention. It would be really good for new contributors.

**Comment by armenzg** [comment]
This is something that @camd is handling.
It was not easy after all.
