### ISSUE TITLE
Disable lint checks or provide a command to auto-fix all of them

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/treeherder#5841]
My PRs include hours devoted to lint fixes.  Let's provide a way to autofix all lint errors, and disable any lint fixes that can not be auto-fixed.

Passing operational tests should be the only requirement.

**Comment by klahnakoski** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1610346

**Comment by Shivansh2407** [comment]
Can I work on this if possible?
