### ISSUE TITLE
Add Python test coverage

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5853]
Shubhank is interested on taking this.

**Comment by armenzg** [comment]
@shubhank-saxena ^

**Comment by shubhank-saxena** [comment]
On it! @armenzg

**Comment by armenzg** [comment]
Hi @shubhank-saxena 
We currently only report Javascript test coverage on https://codecov.io/gh/mozilla/treeherder

Would you mind investigating what it would take to also report the Python test coverage?
Not sure if the two can distinct languages can be reported together.

You can probably fork this repo and create your own account for Travis and codecov. The Travis results are submitted to codecov. You would have to make your GH fork report to your codecov account.

**Comment by shubhank-saxena** [comment]
Hello @armenzg 
With my initial inspection and understanding of codecov, we definitely can split all of our Travis Tests in frontend and backend, and then can write codecov yaml file according to the language that needs to be parsed.
So that means, we are just evaluating the frontend(react) and reporting it to codecov. We can now label and split our entire project in frontend and backend, and write yaml for both respectively!
Let me fork and work and will post the observations here.
Cheers!

**Comment by shubhank-saxena** [comment]
@armenzg I have tried various ways to flush the xml file to codecov repo, but this error keeps popping up. This looks like some issue in the responses library. Any suggestions to work around this?

![Screenshot from 2020-01-23 03-15-23](https://user-images.githubusercontent.com/29003047/72937226-bc2df400-3d8e-11ea-9014-979a4c8dea47.png)

**Comment by shubhank-saxena** [comment]
This is my modified travis.yml file for running python-tests-main 
![Screenshot from 2020-01-23 03-28-10](https://user-images.githubusercontent.com/29003047/72938201-8be75500-3d90-11ea-9059-aa4ca1a2fe68.png)

**Comment by armenzg** [comment]
Try this:
```
docker-compose run backend bash
pytest tests/ --runslow --ignore=tests/selenium/
pytest --cov=./ --cov-report=xml
```

Notice that you tried running pytest outside of the docker container and you use Python 2.7 rather than Python 3

**Comment by armenzg** [comment]
I can't see [this image](https://user-images.githubusercontent.com/29003047/72938201-8be75500-3d90-11ea-9059-aa4ca1a2fe68.png) anymore.

Modify requirements/dev.txt instead of adding `pip install` lines.

**Comment by shubhank-saxena** [comment]
Okay! Let me correct it

**Comment by shubhank-saxena** [comment]
How do you add hash values along with the requirements in requirements/dev.txt @armenzg ?

**Comment by armenzg** [comment]
It's a pain of a process.

Enter into the container (`docker-compose run backend bash`), change the version in the file, run `pip install -r requirements/dev.txt` and it should fail saying that the hashes don't match *and* you will see the two hashes compared. Grab the one that is not found in the requirements file.

**Comment by shubhank-saxena** [comment]
Got one hash value. Re-run the code. Got an error along with another hash value. Appended it and re-run. Still got the issue. Am I doing anything wrong in this?
![Screenshot from 2020-01-24 02-22-43](https://user-images.githubusercontent.com/29003047/73023188-feb80500-3e50-11ea-8be1-edd355bfa93c.png)
![Screenshot from 2020-01-24 02-22-58](https://user-images.githubusercontent.com/29003047/73023192-011a5f00-3e51-11ea-88f4-1fdf15542aa1.png)

**Comment by shubhank-saxena** [comment]
codecov==2.0.15 \    
   --hash=sha256:ae00d68e18d8a20e9c3288ba3875ae03db3a8e892115bf9b83ef20507732bed4 \  
   --hash=sha256=d649dc0bcace6fcdb446ae02b98798a856593b19b637c1b9af8edadf2b150bea
`

**Comment by armenzg** [comment]
Would you be able to start a PR? It's easier for me to see what your work in progress looks like. You can create it as a Draft PR to indicate that is not ready to be reviewed.

Also notice that you will need to add the whole hierarchy of packages with their hashes.

**Comment by shubhank-saxena** [comment]
Started the draft PR. This is the commit
https://github.com/mozilla/treeherder/pull/5860/commits/2c3fbd53421075b839d2c9e2e787c42dbb8763be

**Comment by armenzg** [comment]
For anyone watching this is going very well.
