### ISSUE TITLE
Fix unit test: test_retry_missing_revision_succeeds

### ISSUE THREAD

**Issue by Shivansh2407** [mozilla/treeherder#5874]
BugZilla Link : https://bugzilla.mozilla.org/show_bug.cgi?id=1307289
This is a bug in the project which needs to be fixed. I am willing to work on it. @armenzg and @klahnakoski Please guide me on how to proceed with this .

**Comment by klahnakoski** [comment]
@Shivansh2407  Thank you for tackling this!  I assume you are able to pass the current test suite locally.  I also assume you can run just one test at a time locally.  Yes?  If not, then I can help you there.

The first step takes time:  Remove the `@pytest.mark.skip` line and set a breakpoint on the first line of the test.  Then step through it until you understand what it is trying to test.  Hopefully, it does not need a working Pulse client (I see a `mock`, so probably not).

**Comment by Shivansh2407** [comment]
Yes @klahnakoski please help me out with running the test one at a time locally.

**Comment by klahnakoski** [comment]
@Shivansh2407 Can I assume you have a IDE for coding and debugging?  If not then use PyCharm.
 
Step through these instructions, and tell me where you get blocked.  
https://github.com/klahnakoski/treeherder/blob/debug/tests/README.md

**Comment by Shivansh2407** [comment]
Thank You sir will do it and let you know .

**Comment by klahnakoski** [comment]
... maybe you are missing instructions that precede those... Let me find the setup docs...

**Comment by klahnakoski** [comment]
Here are the setup docs:

https://treeherder.readthedocs.io/installation.html#server-and-full-stack-development

The only thing you should need for this backend work is to fork-and-clone the git repo, and install docker/docker-compose

**Comment by klahnakoski** [comment]
Since my instructions assume my PR is already merged (which it is not), it will be missing the scripts to set the environment variables.   Here is the PR, so you can cut-and-paste 

https://github.com/mozilla/treeherder/pull/5716/files#diff-2fbd99a248bc77b50b89bde69cc4332e

**Comment by klahnakoski** [comment]
Nope, I was wrong again.  My PR is more than just docs, it also opens up the ports on the docker images so things work.   It is best to start with my `debug` PR and work off of that.  Once you have something working, we can rebase to treeherder master

Ensure you are on clean `master

```
git checkout master
git checkout -b debug
git pull https://github.com/klahnakoski/treeherder.git debug
```

you can then merge your work into your local debug branch

**Comment by Shivansh2407** [comment]
Sir can you please guide me further on this?

**Comment by klahnakoski** [comment]
@Shivansh2407   how about you keep this PR open until https://github.com/mozilla/treeherder/pull/5716/  gets merged so it is easier to run tests locally, @camd is very busy.

**Comment by armenzg** [comment]
You can run the test by following these steps:

```
docker-compose run backend bash
pytest tests/test_worker/test_pulse_tasks.py
```

You don't need to wait for that PR to land first.

**Comment by armenzg** [comment]
It exists in Bugzilla let's close the issue here.
