### ISSUE TITLE
Remove NoOpSerializer from serializers.py

### ISSUE THREAD

**Issue by Shivansh2407** [mozilla/treeherder#5886]
BugZilla Link : https://bugzilla.mozilla.org/show_bug.cgi?id=1444093

This issue states to remove NoOpSerializer from serializers.py .

**Comment by Shivansh2407** [comment]
Please review @camd , @armenzg , @klahnakoski .

**Comment by armenzg** [comment]
Please try to ask review of only one reviewer at a time. If we don't get back to you within a business day you can ask again or ask one more person.
You can look at the blame or history of a file to determine who.

**Comment by Shivansh2407** [comment]
Ok @armenzg Sir
