### ISSUE TITLE
Minimum UI coverage

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5912]
Changes:
- A PR should not be merged if it drops the UI test coverage below 40%
- The [relative coverage change](https://docs.codecov.io/docs/codecov-delta#section-relative) should be greater than 0%
  - This means that new lines added are at least somewhat covered; that way we force ourselves to at leat try to write some tests

As always, administratros can still force a merge if needed.

**Comment by shubhank-saxena** [comment]
I would love to take up this @armenzg

**Comment by shubhank-saxena** [comment]
So is the requirement in form of a Github bot?

**Comment by shubhank-saxena** [comment]
@armenzg 
https://github.com/mozilla/treeherder/pull/5914

**Comment by shubhank-saxena** [comment]
@armenzg cleaned everything. New issue- 
#5922

**Comment by armenzg** [comment]
We landed this.
