### ISSUE TITLE
Initialize some defaults for local development

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#5926]
In [this PR](BROKER_URL=localhost//guest:guest@rabbitmq//;DATABASE_URL=mysql://root@localhost:3306/treeherder;REDIS_URL=redis://localhost:6379;SITE_URL=http://backend:8000/;TREEHERDER_DEBUG=True;TREEHERDER_DJANGO_SECRET_KEY=secret-key-of-at-least-50-characters-to-pass-check-deploy;NEW_RELIC_DEVELOPER_MODE=True), there are a bunch of env variables that are manually set up:

> BROKER_URL=localhost//guest:guest@rabbitmq//;DATABASE_URL=mysql://root@localhost:3306/treeherder;REDIS_URL=redis://localhost:6379;SITE_URL=http://backend:8000/;TREEHERDER_DEBUG=True;TREEHERDER_DJANGO_SECRET_KEY=secret-key-of-at-least-50-characters-to-pass-check-deploy;NEW_RELIC_DEVELOPER_MODE=True

Let's set up these defaults in `treeherder/config/settings.py`.

STR:
```bash
python3 -m venv venv # This only works for Python 3
source venv/bin/activate
pip install -r requirements/common.txt
pip install -r requirements/dev.txt
./manage.py check # This is the step that needs to work
```

**Comment by shubhank-saxena** [comment]
Would love to give it a whirl @armenzg

**Comment by armenzg** [comment]
Assigned! Thanks!

**Comment by shubhank-saxena** [comment]
@armenzg 
PR #5942

**Comment by shubhank-saxena** [comment]
Issue #5982

**Comment by armenzg** [comment]
This got fixed a while ago. Thanks!
