### ISSUE TITLE
isort does not behave the same within pre-commit context

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#6112]
This means that pre commit checks complain in one way while `isort` inside of the Docker container complains about other issues.

I'm investigating this as it is quite painful.

**Comment by imskr** [comment]
@armenzg Can I take this issue?

**Comment by shubhank-saxena** [comment]
I am working on this issue. If you want, we can solve it together 😁

**Comment by armenzg** [comment]
I believe I managed to [fix](https://github.com/mozilla/treeherder/blob/master/.pre-commit-config.yaml#L10) running `isort` inside of a venv vs running it as part of Docker.

Nevertheless, I believe I never got pre-commit's isort to behave exactly as just running isort.

In the output below you will see that just running isort does not fix anything while isort within pre-commit touches all files.

You might be able to use `verbose` in [here](https://github.com/mozilla/treeherder/blob/master/setup.cfg#L8-L13) or `.pre-commit-config.yaml` to determine why they differ.

```shell
(.venv) armenzg@Armens-MacBook-Pro treeherder % isort
Skipped 72 files
(.venv) armenzg@Armens-MacBook-Pro treeherder % pre-commit run --all-files isort
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing treeherder/model/migrations/0001_squashed_0022_modify_bugscache_and_bugjobmap.py
Fixing treeherder/perf/migrations/0008_add_confirming_state.py
Fixing treeherder/perf/migrations/0020_add_application_field.py
Fixing treeherder/model/migrations/0015_add_repository_tc_root_url.py
Fixing treeherder/perf/migrations/0007_star_performancealert.py
Fixing treeherder/perf/migrations/0009_non_nullable_issue_tracker.py
Fixing treeherder/perf/migrations/0001_squashed_0005_permit_github_links.py
Fixing treeherder/perf/migrations/0022_add_test_display_names.py
Fixing treeherder/perf/migrations/0024_support_backfill_reports.py
Fixing treeherder/changelog/migrations/0001_initial.py
Fixing treeherder/model/migrations/0013_add_index_to_push_revision.py
Fixing treeherder/perf/migrations/0027_support_perfherder_settings.py
Fixing treeherder/perf/migrations/0018_add_measurement_units.py
Fixing treeherder/perf/migrations/0019_remove_confirming_state.py
Fixing treeherder/model/migrations/0012_branch_maxlen.py
Fixing treeherder/model/migrations/0002_add_bugjobmap_model_manager.py
Fixing treeherder/perf/migrations/0015_add_bug_updated_field.py
Fixing treeherder/perf/migrations/0025_provide_tag_support.py
Fixing treeherder/perf/migrations/0013_add_alert_timestamps.py
Fixing treeherder/model/migrations/0016_add_index_commit_revision.py
Fixing treeherder/seta/migrations/0001_squashed_0002_remove_task_request_and_jp_timeout.py
Fixing treeherder/perf/migrations/0026_add_backfill_record_status.py
Fixing treeherder/model/migrations/0003_add_matcher_name_fields.py
Fixing treeherder/perf/migrations/0023_increase_extra_options_size.py
Fixing treeherder/perf/migrations/0014_add_performance_datum_idx.py
Fixing treeherder/model/migrations/0009_add_manager_to_push_and_job.py
Fixing treeherder/perf/migrations/0011_inc_extra_options_length.py
Fixing treeherder/perf/migrations/0016_modify_alertsummary_status_choices.py
Fixing treeherder/perf/migrations/0006_add_alert_summary_notes.py
Fixing treeherder/model/migrations/0014_add_job_log_status_skipped_size.py
Fixing treeherder/perf/migrations/0017_assignment_support_for_alert_summaries.py
```

**Comment by shubhank-saxena** [comment]
@imskr I am already working on it 😁

**Comment by imskr** [comment]
Is there any issue which I can work which is unassigned 😂 @shubhank-saxena you should get yourself assigned before working on any issue.

**Comment by imskr** [comment]
Please take only one issue at a time @shubhank-saxena

**Comment by shubhank-saxena** [comment]
We have actually had this conversation in the month beginning. The work goes in a given flow. And that's already discussed with the mentors. So, yeah, I work parallel to optimize

**Comment by imskr** [comment]
Then you should get yourself assigned so that other contributors don't get confused.

**Comment by shubhank-saxena** [comment]
Kindly refer to the chats in the Riots. Mentors are usually busy, so that's why we start the work, and mentor then allot us later 
That's why, as I previously said, it's a good practice to ask first in the group, and then get yourself assigned

**Comment by imskr** [comment]
I understand your point but there are lots of messages in chat room. We can't read every single. Its better to atleast comment on the issue here that you are working :)  So that other don't get confused.

**Comment by armenzg** [comment]
Gentlemen,
Please take a moment to breath and before replying any further.

This was my fault. Please forgive me.

Please help me not to forget we assign an issue before working on it.

**Comment by shubhank-saxena** [comment]
@imskr will keep that in mind. Next time, just ask in the group. That will help! Apologies if I sounded rude at any point of time!

**Comment by shubhank-saxena** [comment]
Refer to the issue #6182

**Comment by armenzg** [comment]
It seems that `black` will be getting rid of `isort`.
https://github.com/mozilla/treeherder/pull/6277
