### ISSUE TITLE
isort needs to have enabled with git add .

### ISSUE THREAD

**Issue by shubhank-saxena** [mozilla/treeherder#6136]
@armenzg 
With the recent addition of pre-commit hooks, a file is modified by isort automatically. This creates another copy of file which automatically needs to go through ```git add .```
Need to add one running command

**Comment by shubhank-saxena** [comment]
![Screenshot from 2020-03-12 02-09-33](https://user-images.githubusercontent.com/29003047/76461804-9627e600-6406-11ea-951e-7b5a734f0432.png)

**Comment by shubhank-saxena** [comment]
![Screenshot from 2020-03-12 02-10-52](https://user-images.githubusercontent.com/29003047/76461887-bc4d8600-6406-11ea-8776-fbcf5046fe80.png)

**Comment by armenzg** [comment]
I just landed this on master:
https://github.com/mozilla/treeherder/pull/6134

It is expected to fix issues for you.
