### ISSUE TITLE
Automatic local ingestion of data

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#6179]
Currently we have two Pulse ingestion scripts and three Celery workers in the Procfile. Setting local ingestion requires starting the `backend` Docker container three times following [manual set up steps](https://treeherder.readthedocs.io/installation.html#running-the-ingestion-tasks).

I would like two more entries in the `docker-compose.yml` file for `pulse` and another one for the `celery` worker. They would each have their own different entryfiles.

**Comment by imskr** [comment]
I would like to fix this 🔧

**Comment by armenzg** [comment]
@imskr has asked to work on this.

**Comment by imskr** [comment]
Thank you

**Comment by armenzg** [comment]
Good job @imskr !

**Comment by imskr** [comment]
Thank you @armenzg
