### ISSUE TITLE
Migrate Push Health to Mozci

### ISSUE THREAD

**Issue by camd** [mozilla/treeherder#6220]
We have back-end python code that calculates whether tasks are intermittent or otherwise known failures.  But the work in `mozci` is better and more detailed.  So we should migrate to using that on the back-end.  We will likely post-process some of the data we getfrom `mozci` to format it in a way that is more conducive to Push Health's needs.

https://bugzilla.mozilla.org/show_bug.cgi?id=1626746

Mozci Treeherder Datasource is now completed: https://github.com/mozilla/mozci/pull/258

Related Issue in mozci:
https://github.com/mozilla/mozci/issues/139

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/RELENG-104)

**Comment by data-sync-user** [comment]
➤ Ben Hearsum commented:

testing jira sync

**Comment by data-sync-user** [comment]
➤ Ben Hearsum commented:

testing jira sync
