### ISSUE TITLE
Improve Expand/Collapse of each metric.

### ISSUE THREAD

**Issue by camd** [mozilla/treeherder#6227]
This is both for UX and for A11y
https://bugzilla.mozilla.org/show_bug.cgi?id=1603171

The fix for this issue is to make the buttons at the top of the page toggle open/close of each of the metrics.  Currently they only open, or scroll the metric into the frame.  The same button should also collapse the metric.

Later, we will not completely hide the metric, just collapse it down to the name only.  But that is beyond the scope of this PR.

**Comment by imrishabh18** [comment]
@camd Hey, should i take up this issue ?

**Comment by linzichao** [comment]
Hi @camd, I improve the expand/collapse as following:

![Jun-18-2020 14-40-47](https://user-images.githubusercontent.com/29457750/84986991-09619680-b172-11ea-9255-eaf1057ca72d.gif)

**Comment by camd** [comment]
@linzichao : Hello, and thank you for your interest in this issue.  We are actually in the middle of a UX rework in this area, so the expanding/collapsing will no longer work this way.

I am sorry you spent time on this issue.  I would recommend only working on issues if they have been assigned to you.  Much of the UI work in this project is being handled by a GSoC intern at the moment.  

If other issues become available in this project in the future, I will assign them a label of "good first issue" without an assignee and they will be available to work on.
