### ISSUE TITLE
Display classification info on hover for classified jobs

### ISSUE THREAD

**Issue by camd** [mozilla/treeherder#6234]
https://bugzilla.mozilla.org/show_bug.cgi?id=1542806

**Comment by Rudresh22** [comment]
Hello, can I work on this issue?

**Comment by SuyashSalampuria** [comment]
Hi @Rudresh22  I don't know if we are ready for this change now. 
@camd  and @sarah-clements will be able to tell it perfectly
You may look [here](https://codetribute.mozilla.org/projects/treeherder)  for good first issues and also ask about them in the #treeherder channel in the matrix
