### ISSUE TITLE
Use better colors rather than default red/green/yellow that are good contrast for a11y.

### ISSUE THREAD

**Issue by camd** [mozilla/treeherder#6247]
Use colors like `darker-info` etc.  May need to add more.

**Comment by jmaher** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1627228

**Comment by gamilton211** [comment]
Hello, I am new to open source programming altogether. Can someone please guide me?

**Comment by shubhank-saxena** [comment]
Hello @gamilton211 ! To follow up the requirements of bug, kindly visit the above link posted by @jmaher . Also, kindly join the [Riot](https://medium.com/@armenzg/join-mozillas-new-chat-rooms-328693ceddb0) for disucssing further! Also for seeing what were the changes in *a11y*, you can check [This](https://github.com/mozilla/treeherder/projects/1)

**Comment by Anupam-USP** [comment]
Hello, as this is in good first issue, can I contribute into this as it seems familiar? Also can someone please help

**Comment by paridhi7** [comment]
Hi @camd @sarah-clements I'm new to Open Source and would like to contribute. Can you please guide me with how to get started on this issue?

**Comment by sarah-clements** [comment]
> Hi @camd @sarah-clements I'm new to Open Source and would like to contribute. Can you please guide me with how to get started on this issue?

Hi @paridhi7, I think camd can you give you a better idea of the requirements for this bug but you'll first need to start by reading through our docs. Please read through the entire development section, which also includes important sections on code style and accessibility: https://treeherder.readthedocs.io/index.html
Note: You only need to use `Yarn` for this task, not `docker`.

If anything is unclear you can ask questions in the matrix #treeherder channel and whomever is available can help.
https://wiki.mozilla.org/Matrix

**Comment by rishishounak** [comment]
If this issue is open i would like to join in i am new and could use some guidance

**Comment by sarah-clements** [comment]
> > Hi @camd @sarah-clements I'm new to Open Source and would like to contribute. Can you please guide me with how to get started on this issue?
> 
> Hi @paridhi7, I think camd can you give you a better idea of the requirements for this bug but you'll first need to start by reading through our docs. Please read through the entire development section, which also includes important sections on code style and accessibility: https://treeherder.readthedocs.io/index.html
> Note: You only need to use `Yarn` for this task, not `docker`.
> 
> If anything is unclear you can ask questions in the matrix #treeherder channel and whomever is available can help.
> https://wiki.mozilla.org/Matrix

@paridhi7 Confirming you'll be working on this? Please let me know so I can assign it to someone else.

**Comment by rishishounak** [comment]
If no one is working on this then could I try

**Comment by paridhi7** [comment]
@sarah-clements you can assign it to someone else.

**Comment by SuyashSalampuria** [comment]
@rishishounak Feel free to work on this :)

**Comment by Nikhil1O1** [comment]
take

**Comment by Nikhil1O1** [comment]
take

**Comment by Nikhil1O1** [comment]
take

**Comment by Nikhil1O1** [comment]
@camd please assign it to me...
I'm willing to take this one

**Comment by Nikhil1O1** [comment]
okay I get it... 
"it's assigned to the first patch automatically"  :p
so where's the code located?
I mean how should i begin?
@camd

**Comment by sarah-clements** [comment]
> okay I get it...
> "it's assigned to the first patch automatically" :p
> so where's the code located?
> I mean how should i begin?

You need to follow the instructions in this comment: https://github.com/mozilla/treeherder/issues/6247#issuecomment-689047495 to get set up. You can start looking at the code for `ui/push-health` in this repo once you've forked it and have your development environment set up. Cam can then give you guidance.

**Comment by radioactive11** [comment]
Hello @sarah-clements , I am new to open source and interested to work on this issue. Can you help me get started. Also @Nikhil1O1 if you ever want to pass on this issue, I'll take it up.

**Comment by Nikhil1O1** [comment]
My environment setup is nearly done. So I will be try to fix this one. However if I'm unable to do so, Then you may take this one

**Comment by Nikhil1O1** [comment]
@sarah-clements  @camd My environment setup is complete, Now about modifying push health to make it better-suited for colour blindness or high contrast mode, Could you give me more details on exactly which file I have to look for the code,
I'm new here and have certainly 0 idea of your codebase

**Comment by Nikhil1O1** [comment]
Moreover, I know that most colour blind people have difficulty in distinguishing Red-Green and Blue-Yellow colour. In the push health, we are actively using Blue and Green I recommend changing it to Black/Pink/White/Red as they will be a viable option.
What do you say?
@camd @sarah-clements

**Comment by sarah-clements** [comment]
@Nikhil1O1 I think red and green are the primary issues, in how they are used in combination to convey good or negative results. Please take a look at our docs, as we've had an intern already do quite a bit of research and work in this area: https://treeherder.readthedocs.io/accessibility.html#accessibility

Looking at the bugzilla bug which was filed 6 months ago, I think this issue has likely been resolved due to the recent redesign of push health. @camd Is there anything in Push Health you think this is still applicable to?

**Comment by Nikhil1O1** [comment]
@sarah-clements  I see, Do let me know if there's anything else I can assist you with.

**Comment by ayushontop** [comment]
is this issue still open ? If yes can you please assign it to me

**Comment by Nikhil1O1** [comment]
No buddy, it's actually been resolved
