### ISSUE TITLE
add taskId to intermittent-failures.html

### ISSUE THREAD

**Issue by escapewindow** [mozilla/treeherder#6285]
Hi,

I'm wondering if we could add the taskcluster taskId, as well as a link, to the intermittent failures page.

My current workflow:
1. go to intermittent bug, where I want to view all the tasks that have been reported against this bug
1. open the intermittent bug filer comment(s)
1. click on the link, to see the intermittent failures
1. click on the `revision`, which brings me to a treeherder view of that revision, often weeks in the past. laptop begins to slow
1. click on the `taskId` in the lower left hand corner, which gets me where I want to go.
1. repeat

I'd love for the intermittent-failures page (or the bug comment) to record the taskIds so I can go straight there, rather than having to load the intermediate pages in between. Is that possible?

**Comment by sarah-clements** [comment]
Filed this in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1690912
