### ISSUE TITLE
Remove deprecation warnings for manual ingestion

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#6290]
Running `./manage.py ingest git-push` throws a bunch of warnings (not exclusive to this script).

Since we have Celery queues, we can simply removing the asyncio complexity and these warnings by not trying to do things with asynchronously:
https://github.com/mozilla/treeherder/commit/75dc375a9367a530824c7e4bf92b667068d55f33

e.g.
- taskcluster/aio/asyncutils.py:17: DeprecationWarning: The object should be created from async function
- aiohttp/connector.py:731: DeprecationWarning: The object should be created from async function
  loop=loop)
- aiohttp/connector.py:736: DeprecationWarning: The object should be created from async function
  resolver = DefaultResolver(loop=self._loop)
- aiohttp/cookiejar.py:55: DeprecationWarning: The object should be created from async function
  super().__init__(loop=loop)

**Comment by sarah-clements** [comment]
Filed a bugzilla bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1690928
