### ISSUE TITLE
Add Fenix to intermittent-failures.html for ui-test intermittents

### ISSUE THREAD

**Issue by AaronMT** [mozilla/treeherder#6369]
Hey folks,

I'm wondering if/how Fenix can be accomidated as a tree added to the intermittent-failures.html view (or perhaps some entirely different simplified page)?

The setup for Fenix is of course different than from what one would find in the other trees (issues on Github, labelling, and current manual process for filing intermittent failures). 

https://treeherder.mozilla.org/#/jobs?repo=fenix

For our team we would be interested in looking at `ui-test opt` [tier 2] failures and treat them as intermittent.  The same graphing would be of interest to us (date of first occurrence, failure count, etc).

I'm curious what kind of support can be added for Fenix, is it possible? If not, I am looking for recommendations on how one might acquire similar data manually then (failure count, first occurrence, etc).

**Comment by sarah-clements** [comment]
I'll address this on buzilla :)
