### ISSUE TITLE
Please remove "opt" when not relevant in the list of platforms

### ISSUE THREAD

**Issue by sylvestre** [mozilla/treeherder#6467]
I understand it is legacy but we should remove it to make life of new contributors easier
(and I am sure it is also confusing for existing developers)

Two examples of confusing messages:
![image](https://user-images.githubusercontent.com/733326/83403262-a1d4e880-a408-11ea-8af9-69276eea9d37.png)
=> Shippable implies opt.

![image](https://user-images.githubusercontent.com/733326/83403306-b5804f00-a408-11ea-92b1-3690982699aa.png)
=> these tasks don't have an debug / opt mode

![image](https://user-images.githubusercontent.com/733326/83403348-ce890000-a408-11ea-97e3-1380a9eeb7ec.png)
=> same for the doc

**Comment by sylvestre** [comment]
@armenzg do you know who could fix  that ?
thanks

**Comment by armenzg** [comment]
@camd do you have some pointers as how this can be fixed? I'm a bit of a lose here.

**Comment by sylvestre** [comment]
@camd ping ? :)

**Comment by sylvestre** [comment]
Someone else was just confused about that on #firefox on slack

**Comment by camd** [comment]
@armenzg Here is where we default to "opt" for anything that doesn't have a label:

https://github.com/mozilla/treeherder/blob/d598ad45447ab03c324d88b259417c435a634e83/treeherder/etl/job_loader.py#L191

So we could experiment with either having that be a blank option.  Or maybe set it to the text of "none" if having it blank causes problems with hashing for some reason.  Then in the UI, if we see "none" we just don't show anything.

This is assuming that anything that SHOULD be `opt` will have a `label` of `opt` in this function.  I'm fairly sure that's going to be true.

**Comment by sylvestre** [comment]
Thanks @camd ! :)

**Comment by camd** [comment]
Absolutely.  :)  @armenzg: Were you going to take on doing this work?  Or would you rather I do it?

**Comment by bhearsum** [comment]
There's also a question about which tasks we should remove `opt` from. Some tasks, like decision/fetch/etc. opt isn't even a collection that makes sense (there's no debug/opt/whatever for them). For these, I think it's pretty clear we should remove it.

For tasks like shippable, they are technically opt, but as @sylvestre said, opt is implied by shippable. For these, I'm less certain. If we consider the collections to be purely controlling strings that show up on treeherder, it seems reasonable to remove them. If this metadata is used for other things, we may have to leave them, and handle it on the treeherder side.

**Comment by bhearsum** [comment]
With #6931 closed, I think everything on the Treeherder side is done. Any remaining jobs that have an undesired `opt` will need to have it removed from their task definition.
