### ISSUE TITLE
Push Health should preserve the order of the commit

### ISSUE THREAD

**Issue by sylvestre** [mozilla/treeherder#6532]
Here, I did a try job:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=728cf9e9d74ef17b20220c4ca4c2ec74e02aa98f
The order is the following:
![image](https://user-images.githubusercontent.com/733326/84891654-7efb3300-b09c-11ea-9dad-507ff8dda089.png)

In push health, it seems to be in alphabetical order on the commit hash.
https://treeherder.mozilla.org/pushhealth.html?revision=728cf9e9d74ef17b20220c4ca4c2ec74e02aa98f&repo=try
![image](https://user-images.githubusercontent.com/733326/84891707-94705d00-b09c-11ea-89e2-50427e8fcc97.png)

As the order matters, we should preserve it in push health too!

**Comment by camd** [comment]
Oh wow, yeah.  That's not good!  I'll work on this.

**Comment by sylvestre** [comment]
Thanks :)
