### ISSUE TITLE
improved UI for subtests in perfherder

### ISSUE THREAD

**Issue by tarekziade** [mozilla/treeherder#6555]
Right now it takes a lot of digging to find then display subtests data on perfherder. I think they should just be there by default, and the user can remove them if they don't want them.

subtests should be displayed by default:

- alongside the main value in the treeherder Performance tab 
- in the graph displayed when we click on the link in the Performance tab (one single link for all values)

**Comment by ionutgoldan** [comment]
This looks like a duplicate of [bug 1316590](https://bugzilla.mozilla.org/show_bug.cgi?id=1316590).

**Comment by tarekziade** [comment]
Another thing that could be done maybe (for the use case where you just clicked on the link in treeherder for a single test)
 is add a button called "Add subtests" and prefill the "Add test data" form with the right project/repo/etc so the subtests are displayed directly and it's clearer where to click?
