### ISSUE TITLE
Progress Notifications

### ISSUE THREAD

**Issue by camd** [mozilla/treeherder#6573]
https://bugzilla.mozilla.org/show_bug.cgi?id=1649820

Change the favicon when new failures or push completes.
Allow users to enable system notifications for these events, as well.

**Comment by jhabarsingh** [comment]
can you assign this to me ?

**Comment by SuyashSalampuria** [comment]
Hi @jhabarsingh , I don't think we are yet ready to solve this currently
However, camd will answer it correctly 
You can look for other issues here
https://codetribute.mozilla.org/projects/treeherder

**Comment by jhabarsingh** [comment]
@SuyashSalampuria  thanks for this link.
