### ISSUE TITLE
Pulse: Docker shared user

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#6722]
Hi @camd @sarah-clements 
There's a [Pulse user](https://github.com/mozilla/treeherder/blob/d025e5851d47c8fd7efad280d2c17f217c2a9548/docker-compose.yml#L104) that is part of the Docker set up. This is to make the development process easier and remove the need to create a user.

When I created this user in Pulse Guardian, I did not share it with you because I wanted to make sure that there was no noisy since we added auto-delete queues when there's no consumer. Unfortunately, I did not spend time why there was sometimes warnings so I never added you.

You will need to create a new user or talk with Dustin to pass the ownership to you as I can't do it.

**Comment by carrycooldude** [comment]
I want to work on this @armenzg

**Comment by sarah-clements** [comment]
> I want to work on this @armenzg

This is not a good bug for contributors to work on. You can find some bugs to work on in https://bugzilla.mozilla.org. Look for bugs with the tag "good first bug" and ask if you can work on the bug.

**Comment by sarah-clements** [comment]
> > I want to work on this @armenzg
> 
> This is not a good bug for contributors to work on. You can find some bugs to work on in https://bugzilla.mozilla.org. Look for bugs with the tag "good first bug" and ask if you can work on the bug (ask in a comment and request info from the triage owner).

**Comment by sarah-clements** [comment]
FYI @camd I've taken care of this.
