### ISSUE TITLE
Add appropriate title to the revision links in push health

### ISSUE THREAD

**Issue by SuyashSalampuria** [mozilla/treeherder#6766]
In push health, we show the shortened revision hashes. 
Add appropriate title to them so that we get appropriate directions on hovering on them.

**Comment by manakwadhwa2002** [comment]
Hello @SuyashSalampuria I can do this please assign this to me.

**Comment by SuyashSalampuria** [comment]
You may proceed on solving this
There's just one hash which does not have an appropriate title in push health opening page

**Comment by manakwadhwa2002** [comment]
@SuyashSalampuria thank you can you please share the path of that file with me ?

**Comment by SuyashSalampuria** [comment]
https://github.com/mozilla/treeherder/blob/master/ui/push-health/CommitHistory.jsx#L91
This is the place which needs changes
