### ISSUE TITLE
Treeherder's `group_results` API is missing tasks with failing groups

### ISSUE THREAD

**Issue by ahal** [mozilla/treeherder#6867]
See this task on this push:
https://treeherder.mozilla.org/jobs?repo=autoland&revision=5cfe11c0659ad92715a8f4eebbda67076b737b70&selectedTaskRun=a0Lw1AH_T9mSnvHxKKKCBg.0

It is not listed in the `group_results` endpoint:
https://treeherder.mozilla.org/api/project/autoland/push/group_results/?revision=5cfe11c0659ad92715a8f4eebbda67076b737b70

I'm not 100% sure that the reason this is missing because it failed, but it seems like a pretty big coincidence for it not to be the reason. This issue will need to be fixed before we can use this API in mozci.

**Comment by ahal** [comment]
Actually I think this doesn't block https://github.com/mozilla/mozci/issues/312 after all, since we fall back to downloading group results manually from the errorsummary files. So we can land that other issue, and then once this is fixed mozci will be automagically faster.

**Comment by sarah-clements** [comment]
Going to close this for now, if you see any more issues please file a bug in bugzilla :)
