### ISSUE TITLE
[BUG] Potential Null Pointer Error

### ISSUE THREAD

**Issue by pigeonsoar** [mozilla/treeherder#6887]
Hi! I found that treeherder/log_parser/management/commands/crossreference_missing.py maybe contains a null pointer error in line 75.
When the `total_jobs = float(first_processed - min_job_id)`  in line 67 didn't executed (In the if statement in line 65), and then `fraction_complete = float(first_processed - job_id) / total_jobs` will cause a error as `total_jobs` is None.

I don't know if it is a potential bug?

**Comment by sarah-clements** [comment]
Thanks for the filing the bug but that file has been removed.
