### ISSUE TITLE
Solve current pip-tools situation

### ISSUE THREAD

**Issue by armenzg** [mozilla/treeherder#6966]
@sarah-clements @ahal  (please CC who you see fit) there are some issues on how `pip-tools` was set up.

`pip-tools` recommends not having requirements.txt files and instead generated on the fly if they're needed.
I don't know how this would play out with dependabot. I think dependabot mainly supports `poetry` and `pipenv` as alternatives to `pip`.

I recommend fully moving to `poetry` or remove `pip-tools` completely.

Please let me know preferred approach.

**Comment by sarah-clements** [comment]
I think lets move towards poetry. This is not urgent, so if you have time to help that'd be great but if you don't that's ok also. :)

**Comment by sarah-clements** [comment]
I'm disabling github issues and going back to Bugzilla as our centralized issue management tool. I've filed a bug to replace this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1690926
